version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - file_storing
      - file_analysis
      - qdrant
  file_storing:
    build: ./file_storing
    volumes:
      - file_storage:/files
  embeddings:
    build: ./embeddings
    ports:
      - "8003:8003"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8003/health"]
      interval: 5s
      timeout: 5s
      retries: 10
  file_analysis:
    build: ./file_analysis
    depends_on:
      - qdrant
      - embeddings
    volumes:
      - file_storage:/files
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6333/collections"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  file_storage:
  qdrant_data:
